### PR TITLE
Add org.apache.commons.logging to units taken from simrel/orbit-aggregation

### PR DESCRIPTION
**Pull request by trancexpress**
Fixes: #339

### CODE REVIEW

**Comment by trancexpress** [comment]
@tjeske , can you take a look here please?

**Comment by cdietrich** [comment]
@trancexpress can you check that with your build

**Comment by iloveeclipse** [comment]
> can you check that with your build

You mean https://github.com/eclipse/Xpect/pull/341?
I would just merge it, or is there any catch?

**Comment by cdietrich** [comment]
Novize I don’t know what exactly you do in your. Build

**Comment by iloveeclipse** [comment]
> Yes but I don’t know what exactly you do in your. Build

We patch the build to build against latest (local) SDK build, that's all the difference.

**Comment by cdietrich** [comment]
I merged and will close here

**Pull request closed without merging**
