### PR TITLE
Java 17 minimal requirement

### PR DESCRIPTION
**Pull request by mehmet-karaman**
This PR is part of issue #365 .. The commit contains all occurences of java 11 (replaced by java 17), in manifest.mf, classpath and pom.xml, org.eclipse.jdt.core.prefs files in the xpect workspace.

### CODE REVIEW

**Comment by cdietrich** [comment]
there is still some

org.eclipse.xtext.example.arithmetics.xpect.tests/.settings/org.eclipse.jdt.core.prefs:org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
and 
.settings/org.eclipse.jdt.ui.prefs:formatter_settings_version=11

**Comment by mehmet-karaman** [comment]
org.eclipse.jdt.core.compiler.codegen.targetPlatform=11 .. (27 matches)..

formatter_settings_version=11 ..  (4 matches)

**Comment by mehmet-karaman** [comment]
I noticed that there are some unwanted changes.. Let me check them before the merge..

**Comment by mehmet-karaman** [comment]
Fixed that.. Had accidentally committed auto generated project files by the import wizard..

**Comment by cdietrich** [comment]
org.eclipse.xpect/META-INF/MANIFEST.MF:Bundle-RequiredExecutionEnvironment: JavaSE-11

**Comment by mehmet-karaman** [comment]
I hope that all are completed now :)

**Review by cdietrich — APPROVED** [review]

**Comment by cdietrich** [comment]
thx @mehmet-karaman

**Pull request merged**
