### PR TITLE
negated editor override; extensions will be included instead of excluded.

### PR DESCRIPTION
**Pull request by mehmet-karaman**
@iloveeclipse please could you check this PR. Is it correct now?

### CODE REVIEW

**Comment by cdietrich** [comment]
am not sure if we want to break existing xpect users. this will break them. correct?

**Comment by iloveeclipse** [comment]
> am not sure if we want to break existing xpect users. this will break them. correct?

No, if (by default) nothing is specified in preferences, nothing will change.

> or will the list be empty, and thus it will be checked?

Exact

> what about adding a flag to the extension point. if i remember correct you are using it.

Which flag?

**Comment by cdietrich** [comment]
can you share the xpect extension point you are using.
(my gedächnis aint so good to remember how it exactly looks like)

**Comment by cdietrich** [comment]
as i said: i dont know who is using xpect and i wonder if we can make this really opt out
can you please grep your plugin.xmls for xpect.

for (IExtensionInfo ext : registry.getExtensions("org.eclipse.xpect.fileExtensions"))

i assume you use that one

**Comment by iloveeclipse** [comment]
> i dont know who is using xpect and i wonder if we can make this really opt out

The patch shouldn't affect anyone, it only works if a *new* preference is set. No one has it set, so no one will be affected.

**Comment by mehmet-karaman** [comment]
I've read out all the implemented extensions in the target:

<fileExtension fileExtension="ecore" xtextLanguageName="org.eclipse.emf.ecore.presentation.EcoreEditorID" xtextRuntimeModule="org.eclipse.xtext.ecore.EcoreRuntimeModule" />
<fileExtension fileExtension="ecore" xtextUiModule="org.eclipse.xtext.ui.ecore.EcoreUiModule" />
<fileExtension fileExtension="xtext" xtextLanguageName="org.eclipse.xtext.Xtext" xtextRuntimeModule="org.eclipse.xtext.XtextRuntimeModule" xtextUiModule="org.eclipse.xtext.xtext.ui.internal.XtextUIModuleInternal" />

But in **runtime** mode i am not able to know, which extension is going to be implemented by the user in the **target platform**. And thats not our only problem, for example a *.sh (shellscript which contains XPECT as text in any combination) is not a dsl file:
image
isXtFile(..) method will return in any case false, but Eclipse will open this file also with the Xpect editor (and then the user will be asked for Xtext Nature etc..)

**Comment by mehmet-karaman** [comment]
The user implements his dsl tests in the **runtime itself**.. In the **runtime** he has also implemented his DSL.. So this extension point won't help us, because when he implements this extension, xpect would notice it only in the target platform. But in most of the cases the target platform doesn't contain the xpect editor..

**Comment by iloveeclipse** [comment]
Just to make sure we are all on same page: this PR is a negation of conditions introduced in https://github.com/eclipse/Xpect/pull/354 that was merged last week, without much trouble.

Instead of providing which files we **shouldn't** open in Xpect editor we provide files that **only** should be opened in Xpect editor **if** the preference is set. 

In both cases **nothing** changes for **anyone** without new preference, and no one has the new preference yet because https://github.com/eclipse/Xpect/pull/354 was merged last week.

**Comment by cdietrich** [comment]
yes, understoof, but if you add more languages you need to remember you have the preference set and opt in for your languages

**Comment by mehmet-karaman** [comment]
+ The included file extensions list?

**Comment by iloveeclipse** [comment]
> @mehmet-karaman : can we have a checkbox "enable xpect editor only for registered file extensions" and implementation would scan through all registered languages in the target platform (once), creates the list and checks the list if the checkbox is enabled?

Damn, I'm now confused again, sorry, too much of different tickets.

Just ignore my comment, I will delete it. Of course in the IDE runtime, where the editor is opened, there are no language extensions configured that only known by the target platform.

**Comment by iloveeclipse** [comment]
Ping?

**Comment by iloveeclipse** [comment]
May be we could proceed here?

**Comment by cdietrich** [comment]
I am on vacation and have no code access
I am still confused about which platform we are talking about 

I thought about the one where the dsls are installed and registered to xpect using xpects extension point

**Comment by iloveeclipse** [comment]
> I thought about the one where the dsls are installed and registered to xpect using xpects extension point

No, we are talking about IDE that is used to develop DSL's, so they aren't installed.

**Comment by cdietrich** [comment]
Hmmmm
My proposal was to take the installed / Registered extensions as a based for an opt out and don’t support others at all (maybe we can have an add. Opt  in)

unfortusltely no feedback from others users so nobody seems to care .

maybe people also don’t install xpect.ui  into their developer tooling but their runtime tooling only

**Comment by mehmet-karaman** [comment]
@cdietrich I've adjusted the solution according to your suggestion. Now it looks more clear and it should be easier to understand what's going on there..

**Comment by mehmet-karaman** [comment]
@cdietrich can you look into the *.target what was changed with my last commit (the build wasn't succesffull due to the 4.33-I repository wasn't reachable, I've had to adjust this to pass the build successfully). Are there any other open questions or are we done with this PR?

**Comment by cdietrich** [comment]
Can I currently have no commit rights due bureaucracy I cannot do anything

**Comment by cdietrich** [comment]
can you please rebase

**Comment by mehmet-karaman** [comment]
Rebase done, build is green again :)

**Comment by cdietrich** [comment]
thx

**Comment by cdietrich** [comment]
hi is mehmets eclipse mail the advantest one?

**Comment by cdietrich** [comment]
https://projects.eclipse.org/projects/modeling.xpect/elections/election-mehmet-emin-karaman-eclipse-xpecttm

**Comment by mehmet-karaman** [comment]
Hi Christian, Thank you for helping me to upggrade to a xpect commiter user..  :)

**Comment by iloveeclipse** [comment]
> https://projects.eclipse.org/projects/modeling.xpect/elections/election-mehmet-emin-karaman-eclipse-xpecttm

`This election failed to receive the required number of votes in the alloted time.`

Are there any news here?

**Comment by cdietrich** [comment]
Next attempts https://projects.eclipse.org/projects/modeling.xpect/elections/election-mehmet-emin-karaman-eclipse-xpecttm-0

**Pull request merged**
