### PR TITLE
GH-264: Xpect files cannot be launched in IDE under Java 9

### PR DESCRIPTION
**Pull request by mor-n4**
See #264.

### CODE REVIEW

**Comment by szarnekow** [comment]
Instead of hand-rolling smth, you may want to consider using io.github.classgraph (see https://github.com/eclipse/xtext-extras/pull/433)

**Comment by mor-n4** [comment]
Yes, @cdietrich already mentioned this is the issue. However, he said it's not in the orbit yet.

**Comment by szarnekow** [comment]
It's available in the latest orbit drops.

**Comment by mor-n4** [comment]
Good!

But then more changes are required than just my small bug fix. Some existing code needs to be replaced. Also a CQ is needed.

I'll have a look. Maybe I can provide something...

**Comment by mor-n4** [comment]
build green:
https://ci.eclipse.org/xpect/job/Xpect/job/GH-264/1/

I'll test this tomorrow with our n4js build.

**Comment by mor-n4** [comment]
@meysholdt please have a look. Thanks!

**Comment by mor-n4** [comment]
@meysholdt 

Just to provide some background:

The original code
```java
		if (classLoader instanceof URLClassLoader) {
			URLClassLoader ucl = (URLClassLoader) classLoader;
```
from `ClasspathUtil.java` isn't compatible with Java 9+ because as of version 9 the system class loader does no longer extend `URLClassLoader`.

**Comment by mor-n4** [comment]
@dhuebner since your are currently working on Xpect, you might also wanna have a quick look. Thanks!

**Comment by cdietrich** [comment]
@mor-n4 you should sign off all commits to get the eca validation running

**Comment by cdietrich** [comment]
also https://ci.eclipse.org/xpect/job/Xpect/job/GH-264/lastSuccessfulBuild/artifact/org.eclipse.xpect.releng/p2-repository/target/repository/plugins/ does not seems to contain classgraph
i assume you have to package that as well.

**Comment by cdietrich** [comment]
also somebody with commit rights should file a (piggy back) CQ for classgraph

**Comment by mor-n4** [comment]
Hab ich gemacht, außer bei dem merge commit.

Muß man das auch für merge commits machen??

**Comment by mor-n4** [comment]
@mmews-n4 just created the CQ. Thanks!

**Comment by dhuebner** [comment]
@mor-n4 I'm not familiar with the ClassGraph API, but your code replacement looks okay. 
What I dislike is a mandatory dependency to the "new" Orbit bundle.
This will cause existing projects to update there target platforms to pick the new dependency.
Would it be an option to first check the instance Type of the classloader and if it's not an URLClassLoader try to use ClassGraph?
Also you mentioned an other solution for the class loader cast exception in #264 
In general I don't like adding dependencies to 3rd party library for a one-liner.

**Comment by dhuebner** [comment]
@mor-n4 
I prefer this simple backward compatible solution https://github.com/eclipse/Xpect/tree/GH-264-simple

**Comment by cdietrich** [comment]
you will pull the new classgraph with Xtext 2.19 anyway.

**Comment by mor-n4** [comment]
@dhuebner 
> In general I don't like adding dependencies to 3rd party library for a one-liner.
Neither do I. That's why I had first implemented a solution without adding a new dependency. See my first commit in this PR.
However, it was proposed to use classgraph which is also used in Xtext. For consistency between the closely related projects I figured it makes sense.

**Comment by dhuebner** [comment]
> you will pull the new classgraph with Xtext 2.19 anyway.

Most customer project with Xpect are using Xtext 2.14 and older.  So it's not a pro argument to me.

**Comment by cdietrich** [comment]
projects with java 11 wont use Xtext 2.14

**Comment by mmews-n4** [comment]
We don't know whether the one-liner is a fully adequate substitute for the graphclass library, also with regard to all versions of Java 9+ (i.e. 10, 11, 12, 13, and beyond).

**Comment by mor-n4** [comment]
@dhuebner

> What I dislike is a mandatory dependency to the "new" Orbit bundle.
> This will cause existing projects to update there target platforms to pick the new dependency.

From what I understand, just the Xpect build is configured to pick classgraph from the Orbit. But some customer project using Xpect and updating to a new version of Xpect (that has the dependency to classgraph) could pick classgraph `4.8.35` from elsewhere, e.g. maven central (as long as that customer project is not an Eclipse project).

**Comment by cdietrich** [comment]
no. this is why i proposed it to package it to the update site e.g. 
https://github.com/eclipse/xtext-umbrella/blob/e217c1c63c0ec67d00a530041e4e093c175a67ed/releng/org.eclipse.xtext.sdk.p2-repository/category.xml#L17

**Comment by dhuebner** [comment]
@mor-n4 I just described my opinion, I'm not reviewing your PR. @meysholdt Will do

**Comment by meysholdt** [comment]
> no. this is why i proposed it to package it to the update site e.g.
> https://github.com/eclipse/xtext-umbrella/blob/e217c1c63c0ec67d00a530041e4e093c175a67ed/releng/org.eclipse.xtext.sdk.p2-repository/category.xml#L17
> and in standalone it will be picked from maven central anyway if you adapt the pom

Xpect could do it in the same way.

**Comment by mor-n4** [comment]
> > no. this is why i proposed it to package it to the update site e.g.
> > https://github.com/eclipse/xtext-umbrella/blob/e217c1c63c0ec67d00a530041e4e093c175a67ed/releng/org.eclipse.xtext.sdk.p2-repository/category.xml#L17
> > and in standalone it will be picked from maven central anyway if you adapt the pom
> 
> Xpect could do it in the same way.

I had already added this when @cdietrich pointed that out the first time. See
https://ci.eclipse.org/xpect/job/Xpect/job/GH-264/5/artifact/org.eclipse.xpect.releng/p2-repository/target/repository/plugins/

**Comment by cdietrich** [comment]
i see maybe add the source too to be consistent

**Comment by mor-n4** [comment]
BTW: if it is true that the original `io.github.classgraph` in version `4.8.35` from some other location like maven central would not work (why? isn't it a problem to have the same ID then?), should we then maybe better add the full version `4.8.35.v20190528-1517` in the manifest of `org.eclipse.xpect` too?

**Comment by cdietrich** [comment]
yes and no: the question is:
- eclipse usecase: no since not in target / installed
- standalone: yes

having the full version in target is a thing of targets so that it wont accept it without qualifier whilst eclipse version policy wants the qualifier and maven does not have it

**Comment by mor-n4** [comment]
@dhuebner 

> @mor-n4 I just described my opinion, I'm not reviewing your PR.

No problem. What you proposed was my initial idea, too, but I can see the advantages the others mentioned (consistency with other projects, etc.).

Any case, thanks for the feedback!

**Comment by mor-n4** [comment]
Recent changes:

1. added the classgraph source to the update site
2. @mmews-n4 created a CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20234

I guess this concludes the discussion and we will later merge this after fixing the eca checker issues.

Thanks everyone for the feedback, esp. @cdietrich for the help!

**Comment by mor-n4** [comment]
Closing this PR; due to problems with eclipse/eca checker it's now replaced by #268 (which contains the exact same changes).

**Pull request closed without merging**
